### ISSUE TITLE
some problem in quantization

### ISSUE THREAD

**Issue by chen-ming2019** [mightydeveloper/Deep-Compression-PyTorch#7]
@mightydeveloper Hi, I used the quantization script in my model .Because of the existing of convolution layer,I encountered an error named as "TypeError: expected dimension <= 2 array or matrix" in using csc_matrix . How to fix the problem? can you give me some advice ? Thank you!

**Comment by xxy90** [comment]
I have the same problem when i apply quantization to the conv layers' weight.

**Comment by Fovever1** [comment]
@chen-ming2019 明哥，实在没办法了，我没您的联系方式，我想问您一下ECO代码的训练集的准确度，希望您能回复我一下，我得到的是top1=78%,top5=91.5%,我看您top1都达到91%，我想询问您一下具体细节！万分感谢！！！

**Comment by YvonneDL** [comment]
> @chen-ming2019 明哥，实在没办法了，我没您的联系方式，我想问您一下ECO代码的训练集的准确度，希望您能回复我一下，我得到的是top1=78%,top5=91.5%,我看您top1都达到91%，我想询问您一下具体细节！万分感谢！！！

实在不好意思，我回答不了你的问题，但是希望你可以帮我看看我的问题，我目前代码没有调通。我的错误是：
PS C:\PycharmProjects\HS_Compression\Deep-Compression-PyTorch-master> python weight_share.py saves/model_after_retraining.ptmodel
Traceback (most recent call last):
  File "C:\PycharmProjects\HS_Compression\Deep-Compression-PyTorch-master\weight_share.py", line 8, in <module>
    import util                                                                                                
  File "C:\PycharmProjects\HS_Compression\Deep-Compression-PyTorch-master\util.py", line 8, in <module>        
    from torchvision import datasets, transforms                                                               
ModuleNotFoundError: No module named 'torchvision'     
但是我确实已经有了“torchvision”这个模块了
